version: 0.1

phases:
      build:
          commands:
             - echo Nothing to do yet


artifacts:
    files:
      - index.html
      - favicon.ico
      - babel.html
      - react.html
      - styles/main.css
      - images/*
